name: Print Keeper Secret Demo

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab
  push:
    branches:
      - main # Also triggers on push to main for easy testing

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Secret Value (Will be masked in logs)
      run: |
        echo "Attempting to print the secret from Keeper..."
        echo "The secret value is: ${{ secrets.KSM_DEMO_SECRET }}"
        echo "If this workflow succeeds, it means the secret was accessed. For security, GitHub Actions automatically masks secret values in logs."
        echo "🎉 This secret value is visible here because the integration with Keeper Secrets Manager is working perfectly! 🎉"
